### ISSUE TITLE
Symbols might hide each other on minified GLSL code

### ISSUE THREAD

**Issue by akikoskinen** [laurentlb/Shader_Minifier#4] opened 2014-05-10 17:18 UTC
The minifier might produce GLSL code similar to this:

```
vec3 m(vec3 m) {
}

vec3 n(vec3 m) {
    return m(m);
}
```

This fails to compile. If I understand it correctly inside the function `n` the name `m` refers to the variable passed as an argument and hides the function name `m`. Hence the function `m` can’t be called from function `n`. I think another name needs to be used for the argument passed to function `n` in order for this to compile successfully.

On another occasion I saw code that looked similar to this:

```
vec3 m(vec3 m) {
}

vec3 n() {
    vec3 m = vec3();
    return m(m);
}
```

A similar problem: inside `n` the local variable `m` hides the function name `m` but `n` still tries to call it. Doesn’t compile.

**Comment by xTr1m** [comment] 2015-09-06 09:44
I second this issue. This should be addressed soon, since it caused us a lot of headaches minutes before the deadline ;)

**Comment by laurentlb** [comment] 2017-04-27 21:00
Do you have a reproducible example?
That would be very useful for fixing the issue!

(Sorry for the delay, development was stopped for a few years, but I'd like to fix the issues now)

**Comment by seece** [comment] 2017-09-20 17:07
I made a crude workaround for this; https://github.com/seece/Shader_Minifier/commit/e0df47fb84aaf98255b19eedab06682ea4a2fbbc
A proper solution should scan the function body and make a list of all functions called and plan the local variable name picks accordingly.

**Comment by laurentlb** [comment] 2023-02-13 23:46
I'll close this issue as obsolete because the bug report is old and I haven't seen this kind of issue recently (I don't remember if we made a fix for this specifically).

Please let me know there are still problems.

**Closed by laurentlb** 2023-02-13 23:46 UTC
